#!/usr/bin/env python3
"""
Process code-review findings JSON → atomic markdowns + GitHub issues.

Idempotent: re-runs skip findings that already carry an issue_url.
State is persisted back into the JSON so future sessions can resume.

Usage:
    python scripts/code-review/process_findings.py docs/code-reviews/data/<file>.json
    python scripts/code-review/process_findings.py docs/code-reviews/data/<file>.json --dry-run
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
import time

# Force UTF-8 for stdout/stderr on Windows so em-dashes / arrows in titles don't crash print().
try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except (AttributeError, Exception):
    pass

ROOT = pathlib.Path(__file__).resolve().parents[2]
FINDINGS_DIR = ROOT / "docs" / "code-reviews" / "findings"
REPO = "napoleonmm83/paperless-scanner"
MILESTONE = "Code Review 2026-05"
REVIEW_DATE = "2026-05-04"


def slugify(text: str, maxlen: int = 60) -> str:
    s = text.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")[:maxlen]


def render_markdown(f: dict) -> str:
    fm = [
        "---",
        f"id: {f['id']}",
        f"title: \"{f['title']}\"",
        f"severity: {f['severity']}",
        f"area: {f['area']}",
        f"subarea: {f.get('subarea', '')}",
        f"file: {f['file']}",
        f"lines: {f['lines']}",
        f"effort: {f['effort']}",
        f"wave: {f.get('wave', 1)}",
        f"github_issue: {f.get('issue_url') or 'pending'}",
        "---",
        "",
        f"# {f['id']} — {f['title']}",
        "",
        f"**Severity:** `{f['severity']}` · **Area:** `{f['area']}/{f.get('subarea','')}` · **Effort:** `{f['effort']}`",
    ]
    if f.get("issue_url"):
        fm.append(f"**Issue:** {f['issue_url']}")
    fm += [
        "",
        "## Location",
        "",
        f"- **File:** `{f['file']}`",
        f"- **Lines:** `{f['lines']}`",
    ]
    if f.get("target"):
        fm.append(f"- **Target:** `{f['target']}`")
    fm += ["", "## Problem", "", f["problem"].strip(), "", "## Proposed Fix", "", f["proposed_fix"].strip(), "", "## Acceptance Criteria", ""]
    for ac in f.get("acceptance_criteria", []):
        fm.append(f"- [ ] {ac}")
    fm += ["", "## Effort", "", f"`{f['effort']}`"]
    if f.get("related"):
        fm += ["", "## Related Findings", ""]
        for r in f["related"]:
            fm.append(f"- {r}")
    fm += [
        "",
        "## Source",
        "",
        f"Generated by deep code review on {REVIEW_DATE} (wave {f.get('wave', 1)}).",
        "See [`REVIEW_2026-05-04.md`](../REVIEW_2026-05-04.md) for the master report.",
        "",
    ]
    return "\n".join(fm)


def render_issue_body(f: dict, md_filename: str) -> str:
    body_parts = [
        "## Context",
        "",
        f["problem"].strip(),
        "",
        "## Location",
        "",
        f"- **File:** `{f['file']}`",
        f"- **Lines:** `{f['lines']}`",
    ]
    if f.get("target"):
        body_parts.append(f"- **Target:** `{f['target']}`")
    body_parts += [
        "",
        "## Proposed Fix",
        "",
        f["proposed_fix"].strip(),
        "",
        "## Acceptance Criteria",
        "",
    ]
    for ac in f.get("acceptance_criteria", []):
        body_parts.append(f"- [ ] {ac}")
    body_parts += [
        "",
        f"**Effort:** `{f['effort']}`",
        "",
        "## References",
        "",
        f"- Detail markdown: [`docs/code-reviews/findings/{md_filename}`](../blob/main/docs/code-reviews/findings/{md_filename})",
        f"- Master report: [`docs/code-reviews/REVIEW_2026-05-04.md`](../blob/main/docs/code-reviews/REVIEW_2026-05-04.md)",
        f"- Generated: deep review {REVIEW_DATE}, wave {f.get('wave', 1)}",
    ]
    if f.get("related"):
        body_parts += ["", "## Related Findings", ""]
        for r in f["related"]:
            body_parts.append(f"- {r}")
    return "\n".join(body_parts)


def issue_title(f: dict) -> str:
    title = f"[{f['severity'].upper()}] {f['area']}: {f['title']}"
    return title[:250]


def create_issue(f: dict, md_filename: str, dry_run: bool = False) -> str | None:
    title = issue_title(f)
    body = render_issue_body(f, md_filename)
    labels = ["code-review", f"severity:{f['severity']}", f"area:{f['area']}"]
    cmd = [
        "gh", "issue", "create",
        "--repo", REPO,
        "--title", title,
        "--body", body,
        "--milestone", MILESTONE,
    ]
    for l in labels:
        cmd += ["--label", l]
    if dry_run:
        print(f"  DRY-RUN would run: gh issue create --title {title!r} (+labels {labels})")
        return None
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, check=True, encoding="utf-8")
        url = r.stdout.strip().splitlines()[-1] if r.stdout.strip() else None
        return url
    except subprocess.CalledProcessError as e:
        print(f"  FAILED for {f['id']}: {e.stderr.strip()}", file=sys.stderr)
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--no-issues", action="store_true", help="Write markdowns only, skip GH issue creation")
    args = ap.parse_args()

    json_path = pathlib.Path(args.json_path).resolve()
    with json_path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)

    findings = data["findings"]
    FINDINGS_DIR.mkdir(parents=True, exist_ok=True)

    written = 0
    issued = 0
    skipped = 0

    for f in findings:
        slug = slugify(f["title"])
        md_filename = f"{f['id']}-{slug}.md"
        md_path = FINDINGS_DIR / md_filename

        # Always (re)write markdown so it stays in sync with JSON
        md_path.write_text(render_markdown(f), encoding="utf-8")
        written += 1

        if f.get("issue_url"):
            skipped += 1
            print(f"SKIP {f['id']} (issue exists: {f['issue_url']})")
            continue

        if args.no_issues:
            print(f"WROTE {md_filename} (no issue)")
            continue

        url = create_issue(f, md_filename, dry_run=args.dry_run)
        if url:
            f["issue_url"] = url
            f["markdown_path"] = f"docs/code-reviews/findings/{md_filename}"
            issued += 1
            md_path.write_text(render_markdown(f), encoding="utf-8")  # rewrite with URL
            print(f"OK   {f['id']} → {url}")
            with json_path.open("w", encoding="utf-8") as fh:
                json.dump(data, fh, indent=2, ensure_ascii=False)
            time.sleep(0.4)

    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)

    print(f"\nDone. Markdowns written: {written}, issues created: {issued}, skipped: {skipped}")


if __name__ == "__main__":
    main()
